# config.yml

markdown: kramdown

title: Scorpio Intelligence
tagline: Everything is Changing
author: 
  name: Scorpio Intelligence
  site: https://scorpiointel.com
  # description: Everything is Changing
  # image: tile.png
  email: ben@scorpiointel.com

repository: scorpio-intel/scorpio-intel.github.io
  
sass:
  folder: _sass
  style: compressed

production_url: https://scorpiointel.com

JB :
  version : 0.3.0

bootstrap:
  assets: true